from typing import Optional, List, Dict, Union

class Element:
    symbol: str
    name: Optional[str]
    n_protons: Optional[int]
    n_neutrons: Optional[int]
    n_electrons: Optional[int]
    atomic_number: Optional[int]
    period: Optional[int]
    group: Optional[int]
    atomic_mass: Optional[float]
    atomic_radius: Optional[float]
    first_ionization_energy: Optional[float]
    element_type: Optional[str]

    def __init__(self,
                 symbol: str,
                 name: Optional[str] = None,
                 n_protons: Optional[int] = None,
                 n_neutrons: Optional[int] = None,
                 n_electrons: Optional[int] = None,
                 atomic_number: Optional[int] = None,
                 period: Optional[int] = None,
                 group: Optional[int] = None,
                 atomic_mass: Optional[float] = None,
                 atomic_radius: Optional[float] = None,
                 first_ionization_energy: Optional[float] = None,
                 element_type: Optional[str] = None):
        self.symbol = symbol
        self.name = name
        self.n_protons = n_protons
        self.n_neutrons = n_neutrons
        self.n_electrons = n_electrons
        self.atomic_number = atomic_number
        self.period = period
        self.group = group
        self.atomic_mass = atomic_mass
        self.atomic_radius = atomic_radius
        self.first_ionization_energy = first_ionization_energy
        self.element_type = element_type
    
    def __repr__(self):
        return self.symbol

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.symbol == other.symbol
        elif isinstance(other, str):
            return self.symbol == other
        else:
            return False

    def __hash__(self):
        return self.symbol.__hash__()

_PeriodicTableElements: List[Element] = [
    Element(symbol='H',
            name='Hydrogen',
            n_protons=1,
            n_neutrons=0,
            n_electrons=1,
            atomic_number=1,
            period=1,
            group=1,
            atomic_mass=1.007,
            atomic_radius=0.79,
            first_ionization_energy=13.5984,
            element_type='Nonmetal'
    ),

    Element(symbol='He',
            name='Helium',
            n_protons=2,
            n_neutrons=2,
            n_electrons=2,
            atomic_number=2,
            period=1,
            group=18,
            atomic_mass=4.002,
            atomic_radius=0.49,
            first_ionization_energy=24.5874,
            element_type='Noble Gas'
    ),

    Element(symbol='Li',
            name='Lithium',
            n_protons=3,
            n_neutrons=4,
            n_electrons=3,
            atomic_number=3,
            period=2,
            group=1,
            atomic_mass=6.941,
            atomic_radius=2.1,
            first_ionization_energy=5.3917,
            element_type='Alkali Metal'
    ),

    Element(symbol='Be',
            name='Beryllium',
            n_protons=4,
            n_neutrons=5,
            n_electrons=4,
            atomic_number=4,
            period=2,
            group=2,
            atomic_mass=9.012,
            atomic_radius=1.4,
            first_ionization_energy=9.3227,
            element_type='Alkaline Earth Metal'
    ),

    Element(symbol='B',
            name='Boron',
            n_protons=5,
            n_neutrons=6,
            n_electrons=5,
            atomic_number=5,
            period=2,
            group=13,
            atomic_mass=10.811,
            atomic_radius=1.2,
            first_ionization_energy=8.298,
            element_type='Metalloid'
    ),

    Element(symbol='C',
            name='Carbon',
            n_protons=6,
            n_neutrons=6,
            n_electrons=6,
            atomic_number=6,
            period=2,
            group=14,
            atomic_mass=12.011,
            atomic_radius=0.91,
            first_ionization_energy=11.2603,
            element_type='Nonmetal'
    ),

    Element(symbol='N',
            name='Nitrogen',
            n_protons=7,
            n_neutrons=7,
            n_electrons=7,
            atomic_number=7,
            period=2,
            group=15,
            atomic_mass=14.007,
            atomic_radius=0.75,
            first_ionization_energy=14.5341,
            element_type='Nonmetal'
    ),

    Element(symbol='O',
            name='Oxygen',
            n_protons=8,
            n_neutrons=8,
            n_electrons=8,
            atomic_number=8,
            period=2,
            group=16,
            atomic_mass=15.999,
            atomic_radius=0.65,
            first_ionization_energy=13.6181,
            element_type='Nonmetal'
    ),

    Element(symbol='F',
            name='Fluorine',
            n_protons=9,
            n_neutrons=10,
            n_electrons=9,
            atomic_number=9,
            period=2,
            group=17,
            atomic_mass=18.998,
            atomic_radius=0.57,
            first_ionization_energy=17.4228,
            element_type='Halogen'
    ),

    Element(symbol='Ne',
            name='Neon',
            n_protons=10,
            n_neutrons=10,
            n_electrons=10,
            atomic_number=10,
            period=2,
            group=18,
            atomic_mass=20.18,
            atomic_radius=0.51,
            first_ionization_energy=21.5645,
            element_type='Noble Gas'
    ),

    Element(symbol='Na',
            name='Sodium',
            n_protons=11,
            n_neutrons=12,
            n_electrons=11,
            atomic_number=11,
            period=3,
            group=1,
            atomic_mass=22.99,
            atomic_radius=2.2,
            first_ionization_energy=5.1391,
            element_type='Alkali Metal'
    ),

    Element(symbol='Mg',
            name='Magnesium',
            n_protons=12,
            n_neutrons=12,
            n_electrons=12,
            atomic_number=12,
            period=3,
            group=2,
            atomic_mass=24.305,
            atomic_radius=1.7,
            first_ionization_energy=7.6462,
            element_type='Alkaline Earth Metal'
    ),

    Element(symbol='Al',
            name='Aluminum',
            n_protons=13,
            n_neutrons=14,
            n_electrons=13,
            atomic_number=13,
            period=3,
            group=13,
            atomic_mass=26.982,
            atomic_radius=1.8,
            first_ionization_energy=5.9858,
            element_type='Metal'
    ),

    Element(symbol='Si',
            name='Silicon',
            n_protons=14,
            n_neutrons=14,
            n_electrons=14,
            atomic_number=14,
            period=3,
            group=14,
            atomic_mass=28.086,
            atomic_radius=1.5,
            first_ionization_energy=8.1517,
            element_type='Metalloid'
    ),

    Element(symbol='P',
            name='Phosphorus',
            n_protons=15,
            n_neutrons=16,
            n_electrons=15,
            atomic_number=15,
            period=3,
            group=15,
            atomic_mass=30.974,
            atomic_radius=1.2,
            first_ionization_energy=10.4867,
            element_type='Nonmetal'
    ),

    Element(symbol='S',
            name='Sulfur',
            n_protons=16,
            n_neutrons=16,
            n_electrons=16,
            atomic_number=16,
            period=3,
            group=16,
            atomic_mass=32.065,
            atomic_radius=1.1,
            first_ionization_energy=10.36,
            element_type='Nonmetal'
    ),

    Element(symbol='Cl',
            name='Chlorine',
            n_protons=17,
            n_neutrons=18,
            n_electrons=17,
            atomic_number=17,
            period=3,
            group=17,
            atomic_mass=35.453,
            atomic_radius=0.97,
            first_ionization_energy=12.9676,
            element_type='Halogen'
    ),

    Element(symbol='Ar',
            name='Argon',
            n_protons=18,
            n_neutrons=22,
            n_electrons=18,
            atomic_number=18,
            period=3,
            group=18,
            atomic_mass=39.948,
            atomic_radius=0.88,
            first_ionization_energy=15.7596,
            element_type='Noble Gas'
    ),

    Element(symbol='K',
            name='Potassium',
            n_protons=19,
            n_neutrons=20,
            n_electrons=19,
            atomic_number=19,
            period=4,
            group=1,
            atomic_mass=39.098,
            atomic_radius=2.8,
            first_ionization_energy=4.3407,
            element_type='Alkali Metal'
    ),

    Element(symbol='Ca',
            name='Calcium',
            n_protons=20,
            n_neutrons=20,
            n_electrons=20,
            atomic_number=20,
            period=4,
            group=2,
            atomic_mass=40.078,
            atomic_radius=2.2,
            first_ionization_energy=6.1132,
            element_type='Alkaline Earth Metal'
    ),

    Element(symbol='Sc',
            name='Scandium',
            n_protons=21,
            n_neutrons=24,
            n_electrons=21,
            atomic_number=21,
            period=4,
            group=3,
            atomic_mass=44.956,
            atomic_radius=2.1,
            first_ionization_energy=6.5615,
            element_type='Transition Metal'
    ),

    Element(symbol='Ti',
            name='Titanium',
            n_protons=22,
            n_neutrons=26,
            n_electrons=22,
            atomic_number=22,
            period=4,
            group=4,
            atomic_mass=47.867,
            atomic_radius=2.0,
            first_ionization_energy=6.8281,
            element_type='Transition Metal'
    ),

    Element(symbol='V',
            name='Vanadium',
            n_protons=23,
            n_neutrons=28,
            n_electrons=23,
            atomic_number=23,
            period=4,
            group=5,
            atomic_mass=50.942,
            atomic_radius=1.9,
            first_ionization_energy=6.7462,
            element_type='Transition Metal'
    ),

    Element(symbol='Cr',
            name='Chromium',
            n_protons=24,
            n_neutrons=28,
            n_electrons=24,
            atomic_number=24,
            period=4,
            group=6,
            atomic_mass=51.996,
            atomic_radius=1.9,
            first_ionization_energy=6.7665,
            element_type='Transition Metal'
    ),

    Element(symbol='Mn',
            name='Manganese',
            n_protons=25,
            n_neutrons=30,
            n_electrons=25,
            atomic_number=25,
            period=4,
            group=7,
            atomic_mass=54.938,
            atomic_radius=1.8,
            first_ionization_energy=7.434,
            element_type='Transition Metal'
    ),

    Element(symbol='Fe',
            name='Iron',
            n_protons=26,
            n_neutrons=30,
            n_electrons=26,
            atomic_number=26,
            period=4,
            group=8,
            atomic_mass=55.845,
            atomic_radius=1.7,
            first_ionization_energy=7.9024,
            element_type='Transition Metal'
    ),

    Element(symbol='Co',
            name='Cobalt',
            n_protons=27,
            n_neutrons=32,
            n_electrons=27,
            atomic_number=27,
            period=4,
            group=9,
            atomic_mass=58.933,
            atomic_radius=1.7,
            first_ionization_energy=7.881,
            element_type='Transition Metal'
    ),

    Element(symbol='Ni',
            name='Nickel',
            n_protons=28,
            n_neutrons=31,
            n_electrons=28,
            atomic_number=28,
            period=4,
            group=10,
            atomic_mass=58.693,
            atomic_radius=1.6,
            first_ionization_energy=7.6398,
            element_type='Transition Metal'
    ),

    Element(symbol='Cu',
            name='Copper',
            n_protons=29,
            n_neutrons=35,
            n_electrons=29,
            atomic_number=29,
            period=4,
            group=11,
            atomic_mass=63.546,
            atomic_radius=1.6,
            first_ionization_energy=7.7264,
            element_type='Transition Metal'
    ),

    Element(symbol='Zn',
            name='Zinc',
            n_protons=30,
            n_neutrons=35,
            n_electrons=30,
            atomic_number=30,
            period=4,
            group=12,
            atomic_mass=65.38,
            atomic_radius=1.5,
            first_ionization_energy=9.3942,
            element_type='Transition Metal'
    ),

    Element(symbol='Ga',
            name='Gallium',
            n_protons=31,
            n_neutrons=39,
            n_electrons=31,
            atomic_number=31,
            period=4,
            group=13,
            atomic_mass=69.723,
            atomic_radius=1.8,
            first_ionization_energy=5.9993,
            element_type='Metal'
    ),

    Element(symbol='Ge',
            name='Germanium',
            n_protons=32,
            n_neutrons=41,
            n_electrons=32,
            atomic_number=32,
            period=4,
            group=14,
            atomic_mass=72.64,
            atomic_radius=1.5,
            first_ionization_energy=7.8994,
            element_type='Metalloid'
    ),

    Element(symbol='As',
            name='Arsenic',
            n_protons=33,
            n_neutrons=42,
            n_electrons=33,
            atomic_number=33,
            period=4,
            group=15,
            atomic_mass=74.922,
            atomic_radius=1.3,
            first_ionization_energy=9.7886,
            element_type='Metalloid'
    ),

    Element(symbol='Se',
            name='Selenium',
            n_protons=34,
            n_neutrons=45,
            n_electrons=34,
            atomic_number=34,
            period=4,
            group=16,
            atomic_mass=78.96,
            atomic_radius=1.2,
            first_ionization_energy=9.7524,
            element_type='Nonmetal'
    ),

    Element(symbol='Br',
            name='Bromine',
            n_protons=35,
            n_neutrons=45,
            n_electrons=35,
            atomic_number=35,
            period=4,
            group=17,
            atomic_mass=79.904,
            atomic_radius=1.1,
            first_ionization_energy=11.8138,
            element_type='Halogen'
    ),

    Element(symbol='Kr',
            name='Krypton',
            n_protons=36,
            n_neutrons=48,
            n_electrons=36,
            atomic_number=36,
            period=4,
            group=18,
            atomic_mass=83.798,
            atomic_radius=1.0,
            first_ionization_energy=13.9996,
            element_type='Noble Gas'
    ),

    Element(symbol='Rb',
            name='Rubidium',
            n_protons=37,
            n_neutrons=48,
            n_electrons=37,
            atomic_number=37,
            period=5,
            group=1,
            atomic_mass=85.468,
            atomic_radius=3.0,
            first_ionization_energy=4.1771,
            element_type='Alkali Metal'
    ),

    Element(symbol='Sr',
            name='Strontium',
            n_protons=38,
            n_neutrons=50,
            n_electrons=38,
            atomic_number=38,
            period=5,
            group=2,
            atomic_mass=87.62,
            atomic_radius=2.5,
            first_ionization_energy=5.6949,
            element_type='Alkaline Earth Metal'
    ),

    Element(symbol='Y',
            name='Yttrium',
            n_protons=39,
            n_neutrons=50,
            n_electrons=39,
            atomic_number=39,
            period=5,
            group=3,
            atomic_mass=88.906,
            atomic_radius=2.3,
            first_ionization_energy=6.2173,
            element_type='Transition Metal'
    ),

    Element(symbol='Zr',
            name='Zirconium',
            n_protons=40,
            n_neutrons=51,
            n_electrons=40,
            atomic_number=40,
            period=5,
            group=4,
            atomic_mass=91.224,
            atomic_radius=2.2,
            first_ionization_energy=6.6339,
            element_type='Transition Metal'
    ),

    Element(symbol='Nb',
            name='Niobium',
            n_protons=41,
            n_neutrons=52,
            n_electrons=41,
            atomic_number=41,
            period=5,
            group=5,
            atomic_mass=92.906,
            atomic_radius=2.1,
            first_ionization_energy=6.7589,
            element_type='Transition Metal'
    ),

    Element(symbol='Mo',
            name='Molybdenum',
            n_protons=42,
            n_neutrons=54,
            n_electrons=42,
            atomic_number=42,
            period=5,
            group=6,
            atomic_mass=95.96,
            atomic_radius=2.0,
            first_ionization_energy=7.0924,
            element_type='Transition Metal'
    ),

    Element(symbol='Tc',
            name='Technetium',
            n_protons=43,
            n_neutrons=55,
            n_electrons=43,
            atomic_number=43,
            period=5,
            group=7,
            atomic_mass=98.0,
            atomic_radius=2.0,
            first_ionization_energy=7.28,
            element_type='Transition Metal'
    ),

    Element(symbol='Ru',
            name='Ruthenium',
            n_protons=44,
            n_neutrons=57,
            n_electrons=44,
            atomic_number=44,
            period=5,
            group=8,
            atomic_mass=101.07,
            atomic_radius=1.9,
            first_ionization_energy=7.3605,
            element_type='Transition Metal'
    ),

    Element(symbol='Rh',
            name='Rhodium',
            n_protons=45,
            n_neutrons=58,
            n_electrons=45,
            atomic_number=45,
            period=5,
            group=9,
            atomic_mass=102.906,
            atomic_radius=1.8,
            first_ionization_energy=7.4589,
            element_type='Transition Metal'
    ),

    Element(symbol='Pd',
            name='Palladium',
            n_protons=46,
            n_neutrons=60,
            n_electrons=46,
            atomic_number=46,
            period=5,
            group=10,
            atomic_mass=106.42,
            atomic_radius=1.8,
            first_ionization_energy=8.3369,
            element_type='Transition Metal'
    ),

    Element(symbol='Ag',
            name='Silver',
            n_protons=47,
            n_neutrons=61,
            n_electrons=47,
            atomic_number=47,
            period=5,
            group=11,
            atomic_mass=107.868,
            atomic_radius=1.8,
            first_ionization_energy=7.5762,
            element_type='Transition Metal'
    ),

    Element(symbol='Cd',
            name='Cadmium',
            n_protons=48,
            n_neutrons=64,
            n_electrons=48,
            atomic_number=48,
            period=5,
            group=12,
            atomic_mass=112.411,
            atomic_radius=1.7,
            first_ionization_energy=8.9938,
            element_type='Transition Metal'
    ),

    Element(symbol='In',
            name='Indium',
            n_protons=49,
            n_neutrons=66,
            n_electrons=49,
            atomic_number=49,
            period=5,
            group=13,
            atomic_mass=114.818,
            atomic_radius=2.0,
            first_ionization_energy=5.7864,
            element_type='Metal'
    ),

    Element(symbol='Sn',
            name='Tin',
            n_protons=50,
            n_neutrons=69,
            n_electrons=50,
            atomic_number=50,
            period=5,
            group=14,
            atomic_mass=118.71,
            atomic_radius=1.7,
            first_ionization_energy=7.3439,
            element_type='Metal'
    ),

    Element(symbol='Sb',
            name='Antimony',
            n_protons=51,
            n_neutrons=71,
            n_electrons=51,
            atomic_number=51,
            period=5,
            group=15,
            atomic_mass=121.76,
            atomic_radius=1.5,
            first_ionization_energy=8.6084,
            element_type='Metalloid'
    ),

    Element(symbol='Te',
            name='Tellurium',
            n_protons=52,
            n_neutrons=76,
            n_electrons=52,
            atomic_number=52,
            period=5,
            group=16,
            atomic_mass=127.6,
            atomic_radius=1.4,
            first_ionization_energy=9.0096,
            element_type='Metalloid'
    ),

    Element(symbol='I',
            name='Iodine',
            n_protons=53,
            n_neutrons=74,
            n_electrons=53,
            atomic_number=53,
            period=5,
            group=17,
            atomic_mass=126.904,
            atomic_radius=1.3,
            first_ionization_energy=10.4513,
            element_type='Halogen'
    ),

    Element(symbol='Xe',
            name='Xenon',
            n_protons=54,
            n_neutrons=77,
            n_electrons=54,
            atomic_number=54,
            period=5,
            group=18,
            atomic_mass=131.293,
            atomic_radius=1.2,
            first_ionization_energy=12.1298,
            element_type='Noble Gas'
    ),

    Element(symbol='Cs',
            name='Cesium',
            n_protons=55,
            n_neutrons=78,
            n_electrons=55,
            atomic_number=55,
            period=6,
            group=1,
            atomic_mass=132.905,
            atomic_radius=3.3,
            first_ionization_energy=3.8939,
            element_type='Alkali Metal'
    ),

    Element(symbol='Ba',
            name='Barium',
            n_protons=56,
            n_neutrons=81,
            n_electrons=56,
            atomic_number=56,
            period=6,
            group=2,
            atomic_mass=137.327,
            atomic_radius=2.8,
            first_ionization_energy=5.2117,
            element_type='Alkaline Earth Metal'
    ),

    Element(symbol='La',
            name='Lanthanum',
            n_protons=57,
            n_neutrons=82,
            n_electrons=57,
            atomic_number=57,
            period=6,
            group=3,
            atomic_mass=138.905,
            atomic_radius=2.7,
            first_ionization_energy=5.5769,
            element_type='Lanthanide'
    ),

    Element(symbol='Ce',
            name='Cerium',
            n_protons=58,
            n_neutrons=82,
            n_electrons=58,
            atomic_number=58,
            period=6,
            group=None,
            atomic_mass=140.116,
            atomic_radius=2.7,
            first_ionization_energy=5.5387,
            element_type='Lanthanide'
    ),

    Element(symbol='Pr',
            name='Praseodymium',
            n_protons=59,
            n_neutrons=82,
            n_electrons=59,
            atomic_number=59,
            period=6,
            group=None,
            atomic_mass=140.908,
            atomic_radius=2.7,
            first_ionization_energy=5.473,
            element_type='Lanthanide'
    ),

    Element(symbol='Nd',
            name='Neodymium',
            n_protons=60,
            n_neutrons=84,
            n_electrons=60,
            atomic_number=60,
            period=6,
            group=None,
            atomic_mass=144.242,
            atomic_radius=2.6,
            first_ionization_energy=5.525,
            element_type='Lanthanide'
    ),

    Element(symbol='Pm',
            name='Promethium',
            n_protons=61,
            n_neutrons=84,
            n_electrons=61,
            atomic_number=61,
            period=6,
            group=None,
            atomic_mass=145.0,
            atomic_radius=2.6,
            first_ionization_energy=5.582,
            element_type='Lanthanide'
    ),

    Element(symbol='Sm',
            name='Samarium',
            n_protons=62,
            n_neutrons=88,
            n_electrons=62,
            atomic_number=62,
            period=6,
            group=None,
            atomic_mass=150.36,
            atomic_radius=2.6,
            first_ionization_energy=5.6437,
            element_type='Lanthanide'
    ),

    Element(symbol='Eu',
            name='Europium',
            n_protons=63,
            n_neutrons=89,
            n_electrons=63,
            atomic_number=63,
            period=6,
            group=None,
            atomic_mass=151.964,
            atomic_radius=2.6,
            first_ionization_energy=5.6704,
            element_type='Lanthanide'
    ),

    Element(symbol='Gd',
            name='Gadolinium',
            n_protons=64,
            n_neutrons=93,
            n_electrons=64,
            atomic_number=64,
            period=6,
            group=None,
            atomic_mass=157.25,
            atomic_radius=2.5,
            first_ionization_energy=6.1501,
            element_type='Lanthanide'
    ),

    Element(symbol='Tb',
            name='Terbium',
            n_protons=65,
            n_neutrons=94,
            n_electrons=65,
            atomic_number=65,
            period=6,
            group=None,
            atomic_mass=158.925,
            atomic_radius=2.5,
            first_ionization_energy=5.8638,
            element_type='Lanthanide'
    ),

    Element(symbol='Dy',
            name='Dysprosium',
            n_protons=66,
            n_neutrons=97,
            n_electrons=66,
            atomic_number=66,
            period=6,
            group=None,
            atomic_mass=162.5,
            atomic_radius=2.5,
            first_ionization_energy=5.9389,
            element_type='Lanthanide'
    ),

    Element(symbol='Ho',
            name='Holmium',
            n_protons=67,
            n_neutrons=98,
            n_electrons=67,
            atomic_number=67,
            period=6,
            group=None,
            atomic_mass=164.93,
            atomic_radius=2.5,
            first_ionization_energy=6.0215,
            element_type='Lanthanide'
    ),

    Element(symbol='Er',
            name='Erbium',
            n_protons=68,
            n_neutrons=99,
            n_electrons=68,
            atomic_number=68,
            period=6,
            group=None,
            atomic_mass=167.259,
            atomic_radius=2.5,
            first_ionization_energy=6.1077,
            element_type='Lanthanide'
    ),

    Element(symbol='Tm',
            name='Thulium',
            n_protons=69,
            n_neutrons=100,
            n_electrons=69,
            atomic_number=69,
            period=6,
            group=None,
            atomic_mass=168.934,
            atomic_radius=2.4,
            first_ionization_energy=6.1843,
            element_type='Lanthanide'
    ),

    Element(symbol='Yb',
            name='Ytterbium',
            n_protons=70,
            n_neutrons=103,
            n_electrons=70,
            atomic_number=70,
            period=6,
            group=None,
            atomic_mass=173.054,
            atomic_radius=2.4,
            first_ionization_energy=6.2542,
            element_type='Lanthanide'
    ),

    Element(symbol='Lu',
            name='Lutetium',
            n_protons=71,
            n_neutrons=104,
            n_electrons=71,
            atomic_number=71,
            period=6,
            group=None,
            atomic_mass=174.967,
            atomic_radius=2.3,
            first_ionization_energy=5.4259,
            element_type='Lanthanide'
    ),

    Element(symbol='Hf',
            name='Hafnium',
            n_protons=72,
            n_neutrons=106,
            n_electrons=72,
            atomic_number=72,
            period=6,
            group=4,
            atomic_mass=178.49,
            atomic_radius=2.2,
            first_ionization_energy=6.8251,
            element_type='Transition Metal'
    ),

    Element(symbol='Ta',
            name='Tantalum',
            n_protons=73,
            n_neutrons=108,
            n_electrons=73,
            atomic_number=73,
            period=6,
            group=5,
            atomic_mass=180.948,
            atomic_radius=2.1,
            first_ionization_energy=7.5496,
            element_type='Transition Metal'
    ),

    Element(symbol='W',
            name='Wolfram',
            n_protons=74,
            n_neutrons=110,
            n_electrons=74,
            atomic_number=74,
            period=6,
            group=6,
            atomic_mass=183.84,
            atomic_radius=2.0,
            first_ionization_energy=7.864,
            element_type='Transition Metal'
    ),

    Element(symbol='Re',
            name='Rhenium',
            n_protons=75,
            n_neutrons=111,
            n_electrons=75,
            atomic_number=75,
            period=6,
            group=7,
            atomic_mass=186.207,
            atomic_radius=2.0,
            first_ionization_energy=7.8335,
            element_type='Transition Metal'
    ),

    Element(symbol='Os',
            name='Osmium',
            n_protons=76,
            n_neutrons=114,
            n_electrons=76,
            atomic_number=76,
            period=6,
            group=8,
            atomic_mass=190.23,
            atomic_radius=1.9,
            first_ionization_energy=8.4382,
            element_type='Transition Metal'
    ),

    Element(symbol='Ir',
            name='Iridium',
            n_protons=77,
            n_neutrons=115,
            n_electrons=77,
            atomic_number=77,
            period=6,
            group=9,
            atomic_mass=192.217,
            atomic_radius=1.9,
            first_ionization_energy=8.967,
            element_type='Transition Metal'
    ),

    Element(symbol='Pt',
            name='Platinum',
            n_protons=78,
            n_neutrons=117,
            n_electrons=78,
            atomic_number=78,
            period=6,
            group=10,
            atomic_mass=195.084,
            atomic_radius=1.8,
            first_ionization_energy=8.9587,
            element_type='Transition Metal'
    ),

    Element(symbol='Au',
            name='Gold',
            n_protons=79,
            n_neutrons=118,
            n_electrons=79,
            atomic_number=79,
            period=6,
            group=11,
            atomic_mass=196.967,
            atomic_radius=1.8,
            first_ionization_energy=9.2255,
            element_type='Transition Metal'
    ),

    Element(symbol='Hg',
            name='Mercury',
            n_protons=80,
            n_neutrons=121,
            n_electrons=80,
            atomic_number=80,
            period=6,
            group=12,
            atomic_mass=200.59,
            atomic_radius=1.8,
            first_ionization_energy=10.4375,
            element_type='Transition Metal'
    ),

    Element(symbol='Tl',
            name='Thallium',
            n_protons=81,
            n_neutrons=123,
            n_electrons=81,
            atomic_number=81,
            period=6,
            group=13,
            atomic_mass=204.383,
            atomic_radius=2.1,
            first_ionization_energy=6.1082,
            element_type='Metal'
    ),

    Element(symbol='Pb',
            name='Lead',
            n_protons=82,
            n_neutrons=125,
            n_electrons=82,
            atomic_number=82,
            period=6,
            group=14,
            atomic_mass=207.2,
            atomic_radius=1.8,
            first_ionization_energy=7.4167,
            element_type='Metal'
    ),

    Element(symbol='Bi',
            name='Bismuth',
            n_protons=83,
            n_neutrons=126,
            n_electrons=83,
            atomic_number=83,
            period=6,
            group=15,
            atomic_mass=208.98,
            atomic_radius=1.6,
            first_ionization_energy=7.2856,
            element_type='Metal'
    ),

    Element(symbol='Po',
            name='Polonium',
            n_protons=84,
            n_neutrons=126,
            n_electrons=84,
            atomic_number=84,
            period=6,
            group=16,
            atomic_mass=210.0,
            atomic_radius=1.5,
            first_ionization_energy=8.417,
            element_type='Metalloid'
    ),

    Element(symbol='At',
            name='Astatine',
            n_protons=85,
            n_neutrons=125,
            n_electrons=85,
            atomic_number=85,
            period=6,
            group=17,
            atomic_mass=210.0,
            atomic_radius=1.4,
            first_ionization_energy=9.3,
            element_type='Noble Gas'
    ),

    Element(symbol='Rn',
            name='Radon',
            n_protons=86,
            n_neutrons=136,
            n_electrons=86,
            atomic_number=86,
            period=6,
            group=18,
            atomic_mass=222.0,
            atomic_radius=1.3,
            first_ionization_energy=10.7485,
            element_type='Alkali Metal'
    ),

    Element(symbol='Fr',
            name='Francium',
            n_protons=87,
            n_neutrons=136,
            n_electrons=87,
            atomic_number=87,
            period=7,
            group=1,
            atomic_mass=223.0,
            atomic_radius=None,
            first_ionization_energy=4.0727,
            element_type='Alkaline Earth Metal'
    ),

    Element(symbol='Ra',
            name='Radium',
            n_protons=88,
            n_neutrons=138,
            n_electrons=88,
            atomic_number=88,
            period=7,
            group=2,
            atomic_mass=226.0,
            atomic_radius=None,
            first_ionization_energy=5.2784,
            element_type='Actinide'
    ),

    Element(symbol='Ac',
            name='Actinium',
            n_protons=89,
            n_neutrons=138,
            n_electrons=89,
            atomic_number=89,
            period=7,
            group=3,
            atomic_mass=227.0,
            atomic_radius=None,
            first_ionization_energy=5.17,
            element_type='Actinide'
    ),

    Element(symbol='Th',
            name='Thorium',
            n_protons=90,
            n_neutrons=142,
            n_electrons=90,
            atomic_number=90,
            period=7,
            group=None,
            atomic_mass=232.038,
            atomic_radius=None,
            first_ionization_energy=6.3067,
            element_type='Actinide'
    ),

    Element(symbol='Pa',
            name='Protactinium',
            n_protons=91,
            n_neutrons=140,
            n_electrons=91,
            atomic_number=91,
            period=7,
            group=None,
            atomic_mass=231.036,
            atomic_radius=None,
            first_ionization_energy=5.89,
            element_type='Actinide'
    ),

    Element(symbol='U',
            name='Uranium',
            n_protons=92,
            n_neutrons=146,
            n_electrons=92,
            atomic_number=92,
            period=7,
            group=None,
            atomic_mass=238.029,
            atomic_radius=None,
            first_ionization_energy=6.1941,
            element_type='Actinide'
    ),

    Element(symbol='Np',
            name='Neptunium',
            n_protons=93,
            n_neutrons=144,
            n_electrons=93,
            atomic_number=93,
            period=7,
            group=None,
            atomic_mass=237.0,
            atomic_radius=None,
            first_ionization_energy=6.2657,
            element_type='Actinide'
    ),

    Element(symbol='Pu',
            name='Plutonium',
            n_protons=94,
            n_neutrons=150,
            n_electrons=94,
            atomic_number=94,
            period=7,
            group=None,
            atomic_mass=244.0,
            atomic_radius=None,
            first_ionization_energy=6.0262,
            element_type='Actinide'
    ),

    Element(symbol='Am',
            name='Americium',
            n_protons=95,
            n_neutrons=148,
            n_electrons=95,
            atomic_number=95,
            period=7,
            group=None,
            atomic_mass=243.0,
            atomic_radius=None,
            first_ionization_energy=5.9738,
            element_type='Actinide'
    ),

    Element(symbol='Cm',
            name='Curium',
            n_protons=96,
            n_neutrons=151,
            n_electrons=96,
            atomic_number=96,
            period=7,
            group=None,
            atomic_mass=247.0,
            atomic_radius=None,
            first_ionization_energy=5.9915,
            element_type='Actinide'
    ),

    Element(symbol='Bk',
            name='Berkelium',
            n_protons=97,
            n_neutrons=150,
            n_electrons=97,
            atomic_number=97,
            period=7,
            group=None,
            atomic_mass=247.0,
            atomic_radius=None,
            first_ionization_energy=6.1979,
            element_type='Actinide'
    ),

    Element(symbol='Cf',
            name='Californium',
            n_protons=98,
            n_neutrons=153,
            n_electrons=98,
            atomic_number=98,
            period=7,
            group=None,
            atomic_mass=251.0,
            atomic_radius=None,
            first_ionization_energy=6.2817,
            element_type='Actinide'
    ),

    Element(symbol='Es',
            name='Einsteinium',
            n_protons=99,
            n_neutrons=153,
            n_electrons=99,
            atomic_number=99,
            period=7,
            group=None,
            atomic_mass=252.0,
            atomic_radius=None,
            first_ionization_energy=6.42,
            element_type='Actinide'
    ),

    Element(symbol='Fm',
            name='Fermium',
            n_protons=100,
            n_neutrons=157,
            n_electrons=100,
            atomic_number=100,
            period=7,
            group=None,
            atomic_mass=257.0,
            atomic_radius=None,
            first_ionization_energy=6.5,
            element_type='Actinide'
    ),

    Element(symbol='Md',
            name='Mendelevium',
            n_protons=101,
            n_neutrons=157,
            n_electrons=101,
            atomic_number=101,
            period=7,
            group=None,
            atomic_mass=258.0,
            atomic_radius=None,
            first_ionization_energy=6.58,
            element_type='Actinide'
    ),

    Element(symbol='No',
            name='Nobelium',
            n_protons=102,
            n_neutrons=157,
            n_electrons=102,
            atomic_number=102,
            period=7,
            group=None,
            atomic_mass=259.0,
            atomic_radius=None,
            first_ionization_energy=6.65,
            element_type='Actinide'
    ),

    Element(symbol='Lr',
            name='Lawrencium',
            n_protons=103,
            n_neutrons=159,
            n_electrons=103,
            atomic_number=103,
            period=7,
            group=None,
            atomic_mass=262.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Actinide'
    ),

    Element(symbol='Rf',
            name='Rutherfordium',
            n_protons=104,
            n_neutrons=157,
            n_electrons=104,
            atomic_number=104,
            period=7,
            group=4,
            atomic_mass=261.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Db',
            name='Dubnium',
            n_protons=105,
            n_neutrons=157,
            n_electrons=105,
            atomic_number=105,
            period=7,
            group=5,
            atomic_mass=262.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Sg',
            name='Seaborgium',
            n_protons=106,
            n_neutrons=160,
            n_electrons=106,
            atomic_number=106,
            period=7,
            group=6,
            atomic_mass=266.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Bh',
            name='Bohrium',
            n_protons=107,
            n_neutrons=157,
            n_electrons=107,
            atomic_number=107,
            period=7,
            group=7,
            atomic_mass=264.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Hs',
            name='Hassium',
            n_protons=108,
            n_neutrons=159,
            n_electrons=108,
            atomic_number=108,
            period=7,
            group=8,
            atomic_mass=267.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Mt',
            name='Meitnerium',
            n_protons=109,
            n_neutrons=159,
            n_electrons=109,
            atomic_number=109,
            period=7,
            group=9,
            atomic_mass=268.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Ds ',
            name='Darmstadtium ',
            n_protons=110,
            n_neutrons=161,
            n_electrons=110,
            atomic_number=110,
            period=7,
            group=10,
            atomic_mass=271.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Rg ',
            name='Roentgenium ',
            n_protons=111,
            n_neutrons=161,
            n_electrons=111,
            atomic_number=111,
            period=7,
            group=11,
            atomic_mass=272.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Cn ',
            name='Copernicium ',
            n_protons=112,
            n_neutrons=173,
            n_electrons=112,
            atomic_number=112,
            period=7,
            group=12,
            atomic_mass=285.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Nh',
            name='Nihonium',
            n_protons=113,
            n_neutrons=171,
            n_electrons=113,
            atomic_number=113,
            period=7,
            group=13,
            atomic_mass=284.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type=None
    ),

    Element(symbol='Fl',
            name='Flerovium',
            n_protons=114,
            n_neutrons=175,
            n_electrons=114,
            atomic_number=114,
            period=7,
            group=14,
            atomic_mass=289.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Mc',
            name='Moscovium',
            n_protons=115,
            n_neutrons=173,
            n_electrons=115,
            atomic_number=115,
            period=7,
            group=15,
            atomic_mass=288.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type=None
    ),

    Element(symbol='Lv',
            name='Livermorium',
            n_protons=116,
            n_neutrons=176,
            n_electrons=116,
            atomic_number=116,
            period=7,
            group=16,
            atomic_mass=292.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Transactinide'
    ),

    Element(symbol='Ts',
            name='Tennessine',
            n_protons=117,
            n_neutrons=178,
            n_electrons=117,
            atomic_number=117,
            period=7,
            group=17,
            atomic_mass=295.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type=None
    ),

    Element(symbol='Og',
            name='Oganesson',
            n_protons=118,
            n_neutrons=176,
            n_electrons=118,
            atomic_number=118,
            period=7,
            group=18,
            atomic_mass=294.0,
            atomic_radius=None,
            first_ionization_energy=None,
            element_type='Noble Gas'
    )
]

class ElementTable():

    def __init__(self, elements: List[Element]):
        self._symbol_dict = {
            elem.symbol : elem for elem in elements
        }

        self._name_dict = {
            elem.name : elem for elem in elements
        }

        self._number_dict = {
            elem.atomic_number : elem for elem in elements
        }

    def items(self):
        return self._symbol_dict.items()

    def keys(self):
        return self._symbol_dict.keys()

    def values(self):
        return self._symbol_dict.values()

    def items_by_number(self):
        return self._number_dict.items()

    def items_by_name(self):
        return self._name_dict.items()

    def elements(self):
        return list([ 
            self._number_dict[i] 
            for i in sorted(self._number_dict.keys())
        ])

    def __iter__(self):
        yield from self.elements()

    def __len__(self):
        return len(self._symbol_dict)

    def __contains__(self, key):
        if isinstance(key, int):
            return (key in self._number_dict)
        elif isinstance(key, Element):
            return self._number_dict[key.symbol]
        return (key in self._symbol_dict)

    def __getitem__(self,key):
        if isinstance(key, int):
            return self._number_dict[key]
        if isinstance(key, Element):
            return self._symbol_dict[key.symbol]
        return self._symbol_dict[key]

PeriodicTable: ElementTable = ElementTable(_PeriodicTableElements)
